<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Platforms>x64;ARM64</Platforms>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <Version>0.3.0</Version>
    <PackageReleaseNotes>
- Bump Community.PowerToys.Run.Plugin.Dependencies to 0.96.1
    </PackageReleaseNotes>
    <Authors>Henrik Lau Eriksson</Authors>
    <Description>This NuGet package simplifies the testing of PowerToys Run Plugins.

It contains interfaces and wrappers for static classes from:

- Wox.Infrastructure.dll
- Wox.Plugin.dll
    </Description>
    <PackageId>Community.PowerToys.Run.Plugin.Abstractions</PackageId>
    <PackageProjectUrl>https://github.com/hlaueriksson/Community.PowerToys.Run.Plugin.Abstractions</PackageProjectUrl>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>plugin;plugins;powertoys;microsoft-powertoys;powertoys-run;powertoys-run-plugin</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>NU5128;PKV0001</NoWarn>
  </PropertyGroup>

  <Import Project="../../Analyzers.props" />

  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="Community.PowerToys.Run.Plugin.Abstractions.props" Pack="true" PackagePath="buildTransitive" />
    <None Include="Community.PowerToys.Run.Plugin.Abstractions.targets" Pack="true" PackagePath="buildTransitive" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\ARM64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.dll" Pack="true" PackagePath="runtimes\win-arm64\lib\net9.0" />
    <None Include="bin\ARM64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.pdb" Pack="true" PackagePath="runtimes\win-arm64\lib\net9.0" />
    <None Include="bin\ARM64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.xml" Pack="true" PackagePath="runtimes\win-arm64\lib\net9.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\x64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.dll" Pack="true" PackagePath="runtimes\win-x64\lib\net9.0" />
    <None Include="bin\x64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.pdb" Pack="true" PackagePath="runtimes\win-x64\lib\net9.0" />
    <None Include="bin\x64\Release\net9.0-windows\Community.PowerToys.Run.Plugin.Abstractions.xml" Pack="true" PackagePath="runtimes\win-x64\lib\net9.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Community.PowerToys.Run.Plugin.Dependencies" Version="0.96.1" />
  </ItemGroup>

</Project>
